name: Build xemu for Nintendo Switch

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up devkitPro
      run: |
        sudo apt-get update
        sudo apt-get install -y devkitpro-pacman
        sudo dkp-pacman -Sy devkitA64 libnx switch-tools

    - name: Build xemu
      run: |
        make -f Makefile.switch

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: xemu-switch
        path: path/to/your/output/xemu.nro
